import { Box, Chip, CircularProgress, Divider, Paper, Stack, Typography } from '@mui/material';
import DescriptionIcon from '@mui/icons-material/Description';
import ListAltIcon from '@mui/icons-material/ListAlt';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import CancelOutlinedIcon from '@mui/icons-material/CancelOutlined';
import DoneAllIcon from '@mui/icons-material/DoneAll';
import { StreamMessage, WorkflowNode, Agent, Connection } from '../App';

interface StreamingPanelProps {
  messages: StreamMessage[];
  nodes: WorkflowNode[];
  agents: Agent[];
  connections: Connection[];
}

export function StreamingPanel({ messages, nodes, agents, connections }: StreamingPanelProps) {
  const getAgentName = (nodeId: string) => {
    const node = nodes.find(n => n.id === nodeId);
    const agent = agents.find(a => a.id === node?.agentId);
    return agent?.name || 'Unknown';
  };

  const formatTimestamp = (timestamp: number) => {
    const date = new Date(timestamp);
    return date.toLocaleTimeString('en-US', { 
      hour: '2-digit', 
      minute: '2-digit',
      second: '2-digit' 
    });
  };

  // Separate outputs from regular messages
  const outputs = messages.filter(m => m.isOutput);
  const regularMessages = messages.filter(m => !m.isOutput);

  return (
    <Box
      width={360}
      borderLeft="1px solid"
      borderColor="divider"
      bgcolor="background.paper"
      display="flex"
      flexDirection="column"
      height="100%"
    >
      <Box px={3} py={3} borderBottom="1px solid" borderColor="divider">
        <Typography variant="h6" fontWeight={600} gutterBottom>
          Data Stream
        </Typography>
        <Typography variant="body2" color="text.secondary">
          Live updates from your workflow connections
        </Typography>
      </Box>

      <Box flex={1} overflow="auto" px={3} py={2}>
        <Stack spacing={3}>
          {outputs.length > 0 && (
            <Box>
              <Stack direction="row" spacing={1} alignItems="center" mb={2}>
                <DescriptionIcon color="action" fontSize="small" />
                <Typography variant="subtitle1" fontWeight={600}>
                  Workflow Outputs
                </Typography>
              </Stack>
              <Stack spacing={2}>
                {outputs.map((output) => (
                  <Paper
                    key={output.id}
                    variant="outlined"
                    sx={{
                      borderWidth: 2,
                      borderColor: output.outputStatus === 'success' ? 'success.light' : 'error.light',
                      backgroundColor: output.outputStatus === 'success' ? 'rgba(34,197,94,0.08)' : 'rgba(239,68,68,0.08)',
                      p: 2.5,
                    }}
                  >
                    <Stack direction="row" spacing={2} alignItems="center" mb={2}>
                      {output.outputStatus === 'success' ? (
                        <CheckCircleIcon color="success" fontSize="small" />
                      ) : (
                        <CancelOutlinedIcon color="error" fontSize="small" />
                      )}
                      <Box flex={1} minWidth={0}>
                        <Stack direction="row" spacing={1} alignItems="center">
                          <Typography fontWeight={600}>
                            workflow_output{output.outputType}
                          </Typography>
                          <Chip
                            label={output.outputStatus === 'success' ? 'Success' : 'Error'}
                            color={output.outputStatus === 'success' ? 'success' : 'error'}
                            size="small"
                          />
                        </Stack>
                        <Typography variant="body2" color="text.secondary">
                          Generated by {getAgentName(output.fromNodeId)}
                        </Typography>
                      </Box>
                    </Stack>
                    <Paper variant="outlined" sx={{ maxHeight: 160, overflow: 'auto', p: 2, mb: 2 }}>
                      <Typography variant="body2" color="text.primary" sx={{ whiteSpace: 'pre-wrap' }}>
                        {output.content}
                      </Typography>
                    </Paper>
                    <Stack direction="row" alignItems="center" justifyContent="space-between">
                      <Typography variant="caption" color="text.secondary">
                        {formatTimestamp(output.timestamp)}
                      </Typography>
                      <Chip label={output.outputType} variant="outlined" size="small" />
                    </Stack>
                  </Paper>
                ))}
              </Stack>
            </Box>
          )}

          {connections.length > 0 && (
            <Box>
              <Stack direction="row" spacing={1} alignItems="center" mb={2}>
                <ListAltIcon color="action" fontSize="small" />
                <Typography variant="subtitle1" fontWeight={600}>
                  Execution Order
                </Typography>
              </Stack>
              <Stack spacing={1.5}>
                {connections.map((connection, index) => {
                  const sourceNode = nodes.find((n) => n.id === connection.sourceId);
                  const targetNode = nodes.find((n) => n.id === connection.targetId);
                  const sourceAgent = agents.find((a) => a.id === sourceNode?.agentId);
                  const targetAgent = agents.find((a) => a.id === targetNode?.agentId);

                  return (
                    <Paper
                      key={connection.id}
                      variant="outlined"
                      sx={{
                        p: 1.5,
                        borderLeft: '4px solid',
                        borderColor: connection.isActive ? 'primary.main' : 'divider',
                        backgroundColor: connection.isActive ? 'rgba(37,99,235,0.08)' : 'transparent',
                      }}
                    >
                      <Stack direction="row" alignItems="center" spacing={1.5}>
                        <Box
                          width={28}
                          height={28}
                          borderRadius="50%"
                          display="flex"
                          alignItems="center"
                          justifyContent="center"
                          bgcolor="rgba(148,163,184,0.3)"
                          fontWeight={600}
                        >
                          {index + 1}
                        </Box>
                        <Typography variant="body2" color="text.primary" noWrap>
                          {sourceAgent?.name || 'Unknown'}
                        </Typography>
                        <ArrowForwardIcon fontSize="small" color="action" />
                        <Typography variant="body2" color="text.primary" noWrap>
                          {targetAgent?.name || 'Unknown'}
                        </Typography>
                        {connection.isActive && <CircularProgress size={18} sx={{ ml: 'auto' }} />}
                      </Stack>
                    </Paper>
                  );
                })}
              </Stack>
            </Box>
          )}

          {messages.length === 0 && connections.length === 0 && (
            <Paper variant="outlined" sx={{ textAlign: 'center', p: 4 }}>
              <ArrowForwardIcon color="disabled" sx={{ fontSize: 40 }} />
              <Typography variant="body1" color="text.secondary" mt={1}>
                No connections yet
              </Typography>
              <Typography variant="body2" color="text.secondary">
                Add connections to build your workflow
              </Typography>
            </Paper>
          )}

          {regularMessages.length > 0 && (
            <Box>
              <Stack direction="row" spacing={1} alignItems="center" mb={2}>
                <Typography variant="subtitle1" fontWeight={600}>
                  Messages
                </Typography>
                <Chip label={messages.length} color="secondary" size="small" />
              </Stack>
              <Stack spacing={2}>
                {regularMessages.map((message) => (
                  <Paper key={message.id} variant="outlined" sx={{ p: 2.5, borderLeft: '4px solid', borderColor: 'success.light' }}>
                    <Stack direction="row" spacing={1} alignItems="center" mb={1}>
                      <Chip label={getAgentName(message.fromNodeId)} size="small" variant="outlined" />
                      <ArrowForwardIcon fontSize="small" color="action" />
                      <Chip label={getAgentName(message.toNodeId)} size="small" variant="outlined" />
                      {message.status === 'streaming' && (
                        <CircularProgress size={18} sx={{ ml: 'auto' }} color="success" />
                      )}
                    </Stack>
                    <Typography
                      variant="body2"
                      color="text.primary"
                      sx={{
                        mb: 1,
                        display: '-webkit-box',
                        WebkitLineClamp: 4,
                        WebkitBoxOrient: 'vertical',
                        overflow: 'hidden',
                        whiteSpace: message.content.includes('\n') ? 'pre-wrap' : 'normal',
                      }}
                    >
                      {message.content}
                    </Typography>
                    <Stack direction="row" alignItems="center" justifyContent="space-between">
                      <Typography variant="caption" color="text.secondary">
                        {formatTimestamp(message.timestamp)}
                      </Typography>
                      {message.status === 'complete' && (
                        <Chip icon={<DoneAllIcon fontSize="small" />} label="Delivered" size="small" color="success" variant="outlined" />
                      )}
                    </Stack>
                  </Paper>
                ))}
              </Stack>
            </Box>
          )}
        </Stack>
      </Box>

      {connections.length > 0 && (
        <Box px={3} py={2} borderTop="1px solid" borderColor="divider" bgcolor="rgba(99,102,241,0.05)">
          <Stack direction="row" alignItems="center" justifyContent="space-between">
            <Typography variant="body2" color="text.secondary">
              Total Connections
            </Typography>
            <Chip label={connections.length} color="primary" size="small" />
          </Stack>
        </Box>
      )}
    </Box>
  );
}
